# Generated by Django 5.1.2 on 2024-11-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('accountnum', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('principle', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
